# -*- coding: utf-8 -*-
"""revlab_tsne120.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_GSbcjt9_AoWU1Kq14o_QNxXohqvuoT5
"""

import pandas as pd
df = pd.read_pickle("drive/My Drive/mshr/d2v60/results1.pkl")
vf = pd.read_pickle("drive/My Drive/mshr/d2v60/revlab_vect_reviews.pkl")

print(df.head())
print(vf.head())

from sklearn.manifold import TSNE
# t-SNE is a unsupervised and non-linear technique
# for data exploration and visualizing high-dimentional data

data = vf.vectors
print(data[0:10])

model = TSNE(n_components=2, random_state=0, perplexity= 120, n_iter = 5000)
# the number of components = 2
# default perplexity = 30
# default learning rate = 200 -> 20
# default maximum number of iterations for the optimization (epsilon) n_iter= 1000

vdf = []
for v in data:
  vdf.append(v)
df = pd.DataFrame(vdf)
print(df.head())

tsne_data = model.fit_transform(df)
tsne_df = pd.DataFrame(data = tsne_data, columns = ('D1', 'D2'))
print(tsne_df.head())

tsne_df.to_pickle("drive/My Drive/mshr/d2v60/test5.pkl")